Save

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -100,50 +100,81 @@
 
   #         name: 
 
-name: CI/CD con Vercel
+# name: CI/CD con Vercel
+
+# on:
+#   push:
+#     branches: [main]
+#   pull_request:
+#     branches: [main]
+#     types: [opened, synchronize]
+
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout del Repositorio
+#         uses: actions/checkout@v2
+#         with:
+#           fetch-depth: 0
+
+#       - name: Configurar Node.js
+#         uses: actions/setup-node@v2
+#         with:
+#           node-version: '16' 
+
+#       - name: Instalar Dependencias
+#         run: npm ci
+
+#       - name: Compilar
+#         run: npm run build
+
+#       - name: Implementar en Vercel
+#         uses: amondnet/vercel-action@v20
+#         with:
+#           vercel-token: 1vtMzDfCmcAfofwzdN6g9v0g
+#           github-deployment: true
+
+#       - name: Verificación de REPLY
+#         run: |
+#           REPLY=""
+#           read -n 1 -p "Set up and deploy “~/work/proyectoFinal/proyectoFinal”? [Y/n] " < /dev/tty
+#           if [[ "${REPLY}" != "y" ]]; then
+#             echo "El valor de la variable 'REPLY' no es 'y'."
+#             exit 1
+#           fi
+      
+#       - name: Notificar en caso de Fallo
+#         if: failure()
+#         run: echo "La implementación falló. Verifica los registros del flujo de trabajo para más detalles."
+
+name: Deploy to Vercel
 
 on:
   push:
-    branches: [main]
+    branches:
+      - main
   pull_request:
-    branches: [main]
-    types: [opened, synchronize]
+    branches:
+      - main
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout del Repositorio
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-
-      - name: Configurar Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16' 
-
-      - name: Instalar Dependencias
+      - uses: actions/checkout@v2
+      - name: Install dependencies
         run: npm ci
-
-      - name: Compilar
+      - name: Build
         run: npm run build
 
-      - name: Implementar en Vercel
-        uses: amondnet/vercel-action@v20
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: vercel/vercel@v2
         with:
-          vercel-token: 1vtMzDfCmcAfofwzdN6g9v0g
-          github-deployment: true
-
-      - name: Verificación de REPLY
-        run: |
-          REPLY=""
-          read -n 1 -p "Set up and deploy “~/work/proyectoFinal/proyectoFinal”? [Y/n] " < /dev/tty
-          if [[ "${REPLY}" != "y" ]]; then
-            echo "El valor de la variable 'REPLY' no es 'y'."
-            exit 1
-          fi
-      
-      - name: Notificar en caso de Fallo
-        if: failure()
-        run: echo "La implementación falló. Verifica los registros del flujo de trabajo para más detalles."
+          token: 1vtMzDfCmcAfofwzdN6g9v0g
+          # project-name: ${{ env.PROJECT_NAME }}
+          env:
+            NODE_ENV: production
